// src/components/Hero.jsx
import React from 'react';
import "../styles/Hero.css";
import mainImage from "../assets/mainImage.png";
const Hero = () => {
    return (React.createElement("div", { className: "HeroWrapper" },
        React.createElement("div", { className: "HeroMain" },
            React.createElement("div", { className: "HeroColumn HeroLeft" },
                React.createElement("div", { className: "hero-signature" }, "</>"),
                React.createElement("div", null,
                    React.createElement("h2", { className: " hero-intro-text" }, `Building Interactive Websites: From Pretty Frontends To Scalable Backends.`),
                    React.createElement("div", { className: "hero-small-text" },
                        React.createElement("span", null, "Designed  by "),
                        React.createElement("strong", null,
                            React.createElement("a", { href: "#who", className: "HeroLinks link-underline" }, "Mouad El Ammari")),
                        React.createElement("br", null),
                        React.createElement("span", null, "Developed by "),
                        React.createElement("strong", null,
                            React.createElement("a", { href: "#who", className: "HeroLinks link-underline" }, "Mouad El Ammari")))),
                React.createElement("ul", { className: "hero-grid" },
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, 'Experience'),
                        " 4 years shipping"),
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, "Languages"),
                        " English/French/Arabic"),
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, "Projects"),
                        " +20 project delivered"),
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, "Technologies Mastered:"),
                        " 10+"),
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, "Degrees"),
                        " BSc Comp Sci + 2 Years 42Network"),
                    React.createElement("li", null,
                        React.createElement("strong", { className: "bolderComforta" }, "Certifications"),
                        " Credly Certified Dev"),
                    React.createElement("li", { style: { gridColumn: "span 2" } },
                        React.createElement("strong", { className: "bolderComforta preserveWhiteSpace" }, "99.9% Debugging Success Rate "),
                        " Okay, okay\u2014let's say 98% to be modest")),
                React.createElement("div", { className: "hero-working-label bolderComforta" },
                    React.createElement("strong", null, "Currently working at:")),
                React.createElement("div", { className: "hero-working" },
                    React.createElement("a", { className: "HeroLinks link-underline ", href: "https://www.ocpgroup.ma/", target: "_blank", rel: "noopener noreferrer" },
                        React.createElement("strong", null, "OCPA")),
                    "\u00A0\u2192 since August 2023")),
            React.createElement("div", { className: "HeroColumn HeroRight" },
                React.createElement("img", { alt: "mainImage", src: mainImage })))));
};
export default Hero;
