import React from "react";
import { useFadeInOnceLoaded } from "../../hooks/useFadeInOnceLoaded";
import "./Previews.css"; // shared variables & utilities
import "./DockerPreview.css"; // this file’s grid + extras
import architectureImg from "../../assets/project-images/preview/dockerArchitecture.png";
function DockerPreview() {
    const fadeClass = useFadeInOnceLoaded(20);
    return (React.createElement("div", { className: `DockerModalContentInner ${fadeClass}` },
        React.createElement("div", { className: "gridTitle" },
            React.createElement("h2", { className: "ModalTitle" }, "Dockerized Environment")),
        React.createElement("div", { className: "gridSubtitle" },
            React.createElement("p", { className: "ModalSubtitle" },
                "Multi-Service Infrastructure with NGINX, MariaDB, Redis & More",
                React.createElement("span", { className: "Approximation" }, "Approx 210h"))),
        React.createElement("section", { className: "ModalSection gridFeatures" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\u2728"),
                "Key Features"),
            React.createElement("ul", { className: "ModalFeatureList" },
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDEE0\uFE0F"),
                    React.createElement("strong", null, "Docker Compose Orchestration"),
                    " \u2014 Multi-container infra with isolated services"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDD10"),
                    React.createElement("strong", null, "NGINX\u2009+\u2009TLSv1.3"),
                    " \u2014 Secure reverse proxy with HTTPS-only access"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDCBE"),
                    React.createElement("strong", null, "MariaDB Database"),
                    " \u2014 Data persistence for WordPress content"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDCE6"),
                    React.createElement("strong", null, "Volumes for Files\u2009&\u2009DB"),
                    " \u2014 Persistent volumes for site & database"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\u2699\uFE0F"),
                    React.createElement("strong", null, "Env-Based Config"),
                    " \u2014 Fully configured via .env variables"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\u267B\uFE0F"),
                    React.createElement("strong", null, "Crash Recovery"),
                    " \u2014 Automatic container restart on failure"))),
        React.createElement("section", { className: "ModalSection gridOverview" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\uD83D\uDCD6"),
                "Project Overview"),
            React.createElement("p", { className: "ModalParagraph" }, "This project is a containerized infra for WordPress deployment, built using Docker Compose as part of the 42 Network\u2019s Inception system admin challenge. It combines a custom reverse proxy, database, CMS, and optional services\u2014all managed through modular Dockerfiles.")),
        React.createElement("section", { className: "ModalSection gridTech" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\uD83D\uDD10"),
                "Tech Stack"),
            React.createElement("div", { className: "ModalTechTags" },
                React.createElement("span", null, "Docker & Compose"),
                React.createElement("span", null, "WordPress + php-fpm"),
                React.createElement("span", null, "NGINX (TLSv1.2/1.3)"),
                React.createElement("span", null, "MariaDB"),
                React.createElement("span", null, "Redis"),
                React.createElement("span", null, "Adminer, phpMyAdmin"))),
        React.createElement("section", { className: "ModalSection gridArchitecture" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\uD83E\uDDF1"),
                "Architecture Preview"),
            React.createElement("img", { src: architectureImg, alt: "Docker architecture diagram", className: "ModalArchitectureImage" })),
        React.createElement("section", { className: "ModalSection gridRun" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\u2699\uFE0F"),
                "How to Run"),
            React.createElement("pre", { className: "ModalCode" },
                React.createElement("code", null, "git clone https://github.com/Poider//Inception-Dockerized-Solutions.git && cd Inception-Dockerized-Solutions/srcs")),
            React.createElement("div", { className: "ModalHint" },
                "For a comprehensive guide, check my\u00A0",
                React.createElement("a", { href: "https://github.com/Poider/Inception-Dockerized-Solutions", target: "_blank", rel: "noopener noreferrer" }, "GitHub"),
                "\u00A0for a step-by-step walkthrough, or\u00A0",
                React.createElement("a", { href: "https://www.linkedin.com/in/mouadelammari/", target: "_blank" }, "contact me"),
                "\u00A0for any questions.")),
        React.createElement("section", { className: "ModalSection gridBackground" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon", style: { marginBottom: "0.4rem" } }, "\u2712\uFE0F"),
                "Project Background"),
            React.createElement("p", { className: "ModalParagraph ParagraphBoxShadowing" }, "Back in time docker orchestration felt like black magic (DevOps wasn\u2019t my turf), but I rolled up my sleeves, learned the ropes, and got it deployed end-to-end. The project served as a crash-course in infrastructure that came in clutch when I later launched Transcendence.")),
        React.createElement("div", { className: "ModalActions" },
            React.createElement("a", { href: "https://github.com/Poider/Inception-Dockerized-Solutions", target: "_blank", className: "ModalBtn" },
                React.createElement("span", null, "\uD83D\uDD17 "),
                "GitHub"))));
}
export default DockerPreview;
