import React from "react";
import { useFadeInOnceLoaded } from "../../hooks/useFadeInOnceLoaded";
import diagram from "../../assets/project-images/preview/rayTracingDiagram.png";
import reflectiveImgs from "../../assets/project-images/preview/reflective.png";
import "./Previews.css";
import "./RayTracingPreview.css";
function RayTracingPreview() {
    const fadeClass = useFadeInOnceLoaded(20);
    return (React.createElement("div", { className: `RayTracerModalContentInner ${fadeClass}` },
        React.createElement("div", { className: "gridTitle" },
            React.createElement("h2", { className: "ModalTitle" }, "Ray Tracing Reality")),
        React.createElement("div", { className: "gridSubtitle" },
            React.createElement("p", { className: "ModalSubtitle" },
                "One of My Most Complex Creations",
                React.createElement("span", { className: "Approximation" }, "Approx 400h"))),
        React.createElement("section", { className: "ModalSection gridFeatures" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\u2728"),
                "Key Features"),
            React.createElement("ul", { className: "ModalFeatureList" },
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDC8E"),
                    React.createElement("strong", null, "Reflection & Refraction"),
                    " \u2014 Accurate light bending & mirror effects via recursive rays"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDCF7"),
                    React.createElement("strong", null, "Depth of Field"),
                    " \u2014 Simulated camera blur for photorealistic focus"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDE0E"),
                    React.createElement("strong", null, "Shadows"),
                    " \u2014 Ray-traced occlusion shadows"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\uD83D\uDD8D\uFE0F"),
                    React.createElement("strong", null, "Anti-Aliasing"),
                    " \u2014 Smooth edge rendering using supersampling"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\u25FC\uFE0F"),
                    React.createElement("strong", null, "Pattern Mapping"),
                    " \u2014 Checkerboards, rings, stripes, gradients"),
                React.createElement("li", null,
                    React.createElement("span", { className: "featureIcon" }, "\u270F\uFE0F"),
                    React.createElement("strong", null, "Custom Scene Files"),
                    " \u2014 Define objects, materials, and lighting with .rt configs"))),
        React.createElement("section", { className: "ModalSection gridExplanation" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon", style: { marginBottom: "0.4rem" } }, "\uD83D\uDD0D"),
                "What is Ray Tracing?"),
            React.createElement("p", { className: "RayTracerParagraph" }, "Ray tracing is a rendering technique that simulates how light behaves in the real world. It works by casting rays from a camera into a 3D scene and calculating how they bounce off surfaces, pass through transparent materials, or get blocked to create shadows. This method produces highly realistic images with effects like reflection, refraction, soft lighting, and accurate shadows \u2014 all based on the physics of light."),
            React.createElement("img", { src: diagram, alt: "Ray Tracing Diagram", className: "RayTracerImage", id: "diagram" })),
        React.createElement("section", { className: "ModalSection gridScreenshots" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\uD83D\uDCF8"),
                "Renders & Outputs"),
            React.createElement("img", { src: reflectiveImgs, alt: "Refraction Preview", className: "ModalGroupedImage" }),
            React.createElement("p", { id: "RefractionCaption", className: "ModalCaption" }, "Example: Index of Refraction from 1.0 to 2.0")),
        React.createElement("section", { className: "ModalSection gridTech" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\uD83E\uDDF0"),
                "Tech Stack"),
            React.createElement("div", { className: "ModalTechTags" },
                React.createElement("span", null, "C"),
                React.createElement("span", null, "MiniLibX (X11)"),
                React.createElement("span", null, "Manual Memory Management"),
                React.createElement("span", null, "Raw Ray Tracing"),
                React.createElement("span", null, "Multistage Renderer"))),
        React.createElement("section", { className: "ModalSection gridRun" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon" }, "\u2699\uFE0F"),
                "How to Run"),
            React.createElement("pre", { className: "ModalCode" },
                React.createElement("code", null, "git clone https://github.com/Poider/miniRt-3D-RayTracer.git && cd miniRt-3D-RayTracer/miniRt/ && make")),
            React.createElement("div", { className: "ModalHint" },
                "For a comprehensive guide, check my\u00A0",
                React.createElement("a", { href: "https://github.com/Poider/Inception-Dockerized-Solutions", target: "_blank", rel: "noopener noreferrer" }, "GitHub"),
                "\u00A0for a step-by-step walkthrough, or\u00A0",
                React.createElement("a", { href: "https://www.linkedin.com/in/mouadelammari/", target: "_blank" }, "contact me"),
                "\u00A0for any questions.")),
        React.createElement("section", { className: "ModalSection gridBackground" },
            React.createElement("h3", null,
                React.createElement("span", { className: "icon ", style: { marginBottom: "0.4rem" } }, "\u2712\uFE0F"),
                "Project Background"),
            React.createElement("p", { className: "ModalParagraph ParagraphBoxShadowing" }, "This ray-tracing engine is one of my proudest creations\u2014its output feels majestic even before you dig into the code. I gravitate toward visual projects because they resonate: people appreciate something beautiful they can see. Fueled by extensive math and physics (my strong suits), I built this engine entirely from scratch\u2014no external frameworks\u2014handling raw mathematical calculations, pixel-by-pixel rendering, recursive ray logic, and realistic light simulation. It remains one of my most complex and rewarding low-level projects.")),
        React.createElement("div", { className: "ModalActions" },
            React.createElement("a", { href: "https://github.com/Poider/3D-RayTracer-Engine", className: "ModalBtn" },
                React.createElement("span", null, "\uD83D\uDD17 "),
                "GitHub"))));
}
export default RayTracingPreview;
